### ISSUE TITLE
cover image gone black

### ISSUE THREAD

**Issue by spidy2356** [Sv443/BetterYTM#103]
### Checklist:

- [ x] I checked [here](https://github.com/Sv443/BetterYTM/issues?q=is%3Aissue+sort%3Aupdated-desc) if there is already an issue for this bug
- [x ] I am using the latest version of BetterYTM
- [x ] I am using the latest version of my browser
- [x ] I was able to reproduce the bug while all my other userscripts or extensions were disabled

### Description of the bug and steps to reproduce:
 when play a music, cover image just get black.
 play any music from music.youtube.com and the cover image are fully blank/black
 

### Environment:
- Browser name & version: Brave (pc)
[Version 1.68.141 Chromium: 127.0.6533.120 (Official Build) (64-bit)](https://brave.com/latest/)
- Userscript version & build number: v2.0.0 

### Other info / screenshots: 
while using script: 
![image](https://github.com/user-attachments/assets/2f496c10-9351-4296-869b-ee5820c93ae7)

while turn it off: 
![image](https://github.com/user-attachments/assets/2875cbb5-4fba-4139-9552-11e912ee6eff)

**Comment by Sv443** [comment]
Hi and thanks for submitting the issue.  
Could you do me a favor and check if the issue is still present in the v2.1 prerelease 1: https://github.com/Sv443/BetterYTM/releases/tag/experimental-2.1.0-pre1  
Because I *think* I fixed this already.  
(Before installing the prerelease, please make sure to back up your configuration using the "export" button in the config menu.)  
  
Also, how did you get your player page to look like that, with that slick gradient in the background? 👀  
I see that my theme changes don't work too well with it so if possible and if it's not too much of a hassle I could adapt it to look better.

**Comment by spidy2356** [comment]
For the look I use this extension also.
https://github.com/KristofferTroncoso/ThemeSong

I will check the pre-release version in morning. Thanks

**Comment by spidy2356** [comment]
edit: I installed pre-release version but still didn't fix this issue.

saying again, if u didn't notice sir

**Comment by Sv443** [comment]
Alright thanks, I'll investigate this issue.  
(Also, I only get notifications for new comments, not edited ones)

**Comment by Sv443** [comment]
Okay so I'm unable to reproduce this issue at all, so could you please go and open your developer tools (usually with F12), go to the Networking tab, enter `maxresdefault` into the filter and reload the page and see if the request succeeds with a 2xx code?  
I'm beginning to think it might be something network related that is blocking the requests.  
  
![image](https://github.com/user-attachments/assets/d9bbecbc-e68b-4eb2-96fb-c24dbc7a0f61)
  
<br>

And while you're at it, please check the "Console" tab in there as well and set the filter to "BetterYTM" and to only show errors, maybe that can tell me more:  
  
![image](https://github.com/user-attachments/assets/d819d736-5daf-4f41-b630-b6c866aac6b3)

**Comment by spidy2356** [comment]
I go to network tab and try to filter out what u said but nothing comes out, so I disable every extension ( this time adblocker also, ublock origin and brave adblocker), now cover images are shown but the script looks like broken. tried both preview and release version. both show same.
![image](https://github.com/user-attachments/assets/ae340576-a987-43d6-bd2a-42e4a38197fe)


so, I tried google chrome instead of brave, with new profile/account. but the script betterytm somehow doesn't load at all.
![image](https://github.com/user-attachments/assets/5ec553af-8821-48cc-83e5-f34c1d867bc6)

now what should I do??

**Comment by spidy2356** [comment]
I think issue got fixed when I change this settings from "only for songs > never", because video songs/albums doesn't effected. so I changed it and issue fixed.
![image](https://github.com/user-attachments/assets/2322cd5e-1de1-4914-8188-9dc270a81cf0)

and still don't know about chrome, why script is not responding or loading and I don't use chrome at all

thanks for ur help

**Comment by spidy2356** [comment]
here the ss from console 
![image](https://github.com/user-attachments/assets/98998c00-2e3d-4011-b0f1-1dff2c729705)

**Comment by Sv443** [comment]
Could you expand that first error please? Also try to check the Network tab again, you don't have to set the filter there, just search for the request to a URL starting with i.ytimg.com and ending in maxresdefault.jpg. If it doesn't show up, reload the page while keeping the developer tools open.  
Sorry for having you jump through these hoops but otherwise I really can't tell what's going on.

**Comment by spidy2356** [comment]
here is console log
![image](https://github.com/user-attachments/assets/249bb34b-f640-4632-85e1-d94b10e1bda9)

found one option on network tab starting with i.ytimg.com but not ended with maxresdefault.jpg
![image](https://github.com/user-attachments/assets/b3a96339-3415-4172-abae-94da5125091c)

**Comment by Sv443** [comment]
If you could do me one last favor and install [this extension](https://chromewebstore.google.com/detail/disable-content-security/ieelmcmcagommplceebfedjlakkhpden) and enable it for YouTube Music and confirm if the issue is still happening I would be pretty sure what it is.  
Right now I think it is either related to the issue #104, or something in your Network is blocking the requests (like a proxy server, router firewall or some other filter from your ISP).  
Either way, the above extension will fix the problems you wrote about [in this comment](https://github.com/Sv443/BetterYTM/issues/103#issuecomment-2306948704) until I can properly fix them.

**Comment by spidy2356** [comment]
I use the extension u mention above, nothing changes at all. but if the the extension enabled then ads not coming, cover image still blank/black, same error in console tab and no jpg url start with 'i.ytimg.com' in network tab

I try this script turn off my adblocker, and it looks like broken somehow, as I told before, even can't open user settings.
![image](https://github.com/user-attachments/assets/41f0053e-315a-4952-8475-efc4b5e53293)

here is the console and network tab image without adblocker, still same error comes as before and still can't see any url end with 'maxresdefault'

![image](https://github.com/user-attachments/assets/dcd4260b-4fe6-496f-9df3-656e5e80d0e6)

![image](https://github.com/user-attachments/assets/598074d3-0a3d-41ba-ac2d-d541e51445a0)

**Comment by spidy2356** [comment]
edit: tried on firefox, there is everything ok. using the unlock origin with default settings and violent monkey (same as brave)
![image](https://github.com/user-attachments/assets/5bff2a51-7d9a-404b-b813-4aac64d9b338)

![image](https://github.com/user-attachments/assets/21107c77-723f-4cef-8198-653d340c23ab)

no cover image blank/black issue and found the URL also. so it's not isp/router/firewall issue. maybe problem with chromuim browsers

**Comment by Sv443** [comment]
Thanks for investigating. Yeah I'm pretty sure now the method that has to be used in Chromium browsers makes it so the Userscript has to obey the more strict rules of the Content-Security-Policy, which it doesn't need to on Firefox.  
I'm currently working on fixing it but meanwhile that extension that I posted should fix the problem. Make sure it is actually activated on YouTube Music so that the icon isn't in greyscale:  
![image](https://github.com/user-attachments/assets/dfb327b8-6aa2-4f16-a34c-c5e175bb3a32)
  
If that still doesn't fix it then I'm sorry to say I'm out of ideas.

**Comment by Sv443** [comment]
Hmm alright, I'm currently implementing a fix in BetterYTM and my dependency library UserUtils and will then create a new prerelease version. I will post another comment once it's available for installation.

**Comment by Sv443** [comment]
Alright the "TrustedHTML" error should be fixed now. You can test the new version here:  
https://github.com/Sv443/BetterYTM/releases/tag/preview-2.1.0-rc1  
  
Please let me know if that fixed it and also make sure to uninstall the "Disable Content-Security-Policy" extension.

**Comment by spidy2356** [comment]
didn't fix yet.
![image](https://github.com/user-attachments/assets/49f8cfd7-5f8a-43b4-97d2-1ca46375e2ad)

![image](https://github.com/user-attachments/assets/a2358922-35df-4a80-a4b1-00fe889a134c)

**Comment by Sv443** [comment]
I added some better error logging in the new version so what you just sent tells me that it has to be some kind of network error.  
  
Which userscript extension do you use? Tampermonkey, Greasemonkey, Violentmonkey, etc.  
I tested with Violentmonkey on Brave and couldn't reproduce this issue at all.  
It might also be another extension that's blocking the requests.  
  
Also, could you expand this part of both types of error messages and send another screenshot?  
  
![image](https://github.com/user-attachments/assets/ed33fb40-f1fd-44b3-9894-9f14b951fbe2)
![image](https://github.com/user-attachments/assets/b7ca53f6-6871-47a1-808b-29e8ebf40c71)

**Comment by spidy2356** [comment]
yes, working with violentmonkey. I used to use tampermonkey, not works with that on brave.

here is the console log with tampermonkey
![image](https://github.com/user-attachments/assets/af444f3e-716d-4332-a30b-4beeb0dbdb83)

I wish it will help u

**Comment by spidy2356** [comment]
tried on new brave profile with fresh install with tampermonkey and ubo. still not works. so it is not working with the extension. not any extension or userscript interfare

**Comment by Sv443** [comment]
Hmm, I just tried to create a fully empty script just to test if it works at all and didn't even get that to work, so I really just can't recommend using Tampermonkey on Brave.  
Either way, I recommend Violentmonkey because it is generally more stable and has better support for the GM APIs I use in my Userscript.  
I'm gonna close this issue since this is out of my control. Thanks again for your help debugging! 😃
